### ISSUE TITLE
Blank widget after auth redirect

### ISSUE THREAD

**Issue by mhuebert** [firebase/firebaseui-web#121]
When a user arrives back at the FirebaseUI widget after authentication, for some period of time—sometimes multiple seconds—they see this blank rectangle with the loading animation:

<img width="723" alt="screenshot 2017-04-04 00 10 24" src="https://cloud.githubusercontent.com/assets/165223/24633898/44aa3c9e-18cb-11e7-9ea6-1b11d023c918.png">

One of my users emailed me a screenshot of this state today, thinking that I had programmed an error into my app.

I think a message should be displayed to indicate the current status or progress, or show a more ordinary loading indicator—something that a user can make sense of.

**Comment by bojeil-google** [comment]
We are using the MDL progress bar: https://getmdl.io/components/#loading-section/progress
You can override the CSS to display your own GIF:
The class: .firebaseui-busy-indicator

**Comment by mhuebert** [comment]
I think the non-intuitiveness may stem from the facts that 
a) this is appearing on a fresh pageload (after a redirect), rather than in an existing panel that is reacting to user input, and
b) the loader is at the top of an empty rectangle, which to an average user may look like some kind of mistake, because there is no text indicating what is happening (eg/ "Loading Account").

The most relevant [Material Design guidelines](https://material.io/guidelines/components/progress-activity.html#progress-activity-behavior) example does include a text label on the animation:
![screenshot 2017-04-04 13 56 13](https://cloud.githubusercontent.com/assets/165223/24655413/7fe7efb8-193e-11e7-93dc-e43148919bf6.png)

As does Gmail:
![screenshot 2017-04-04 13 57 46](https://cloud.githubusercontent.com/assets/165223/24655480/c32deb06-193e-11e7-8f3b-b0c547f7d18a.png)

And I would reiterate that I have received complaints from ordinary users who believed that even though this flow did sign them in to the app, there must have been an error somewhere because they interpreted the blank rectangle as some kind of mistake or error condition of the app.

**Comment by goodpic** [comment]
Thanks @gbittmann for the example! It helped me to quickly fix it. I slightly modified to wrap the CSS (using SCSS) since I use mdl-shadow--2dp on the other places. 

```css
#firebaseui-auth-container {
  .firebaseui-info-bar {
    margin-top: 20px;
  }

  .mdl-shadow--2dp {
    box-shadow: none;
  }

  .mdl-progress {
    height: 5px;
  }

  div.mdl-progress::after {
    color: black;
    content: 'Authenticating';
    display: block;
    margin: 20px auto;
    text-align: center;
  }
}
```
