### ISSUE TITLE
Streamlining sign in with Google (under Cordova)

### ISSUE THREAD

**Issue by rtm** [firebase/firebaseui-web#442]
My client is complaining that "sign in with Google" in my Cordova app is overly jerky, and I can't disagree.

When I click it:

1. I get a quick progress indication across the top of the firebase UI display.
1. I get an empty page with a progress indication across the top.
1. I get my app's splashscreen.
1. I see my app's sign-in screen again, with the firebase UI display area having a progress display across the top, but the area itself is empty (white/blank--this white background appears to be coming from a `mdl-card` class on `.firebaseui-container`). 

Is there anything I can do to streamline this?

(Actually, this problem is not limited to Sign in with Google; Sign in with Twitter works almost exactly the same way.)

A different issue: when using "sign in with email", after I input my email, it goes to a display where I am supposed to enter my password, but there's no "cancel" button here like there was on the previous screen for entering the email.

**Comment by wti806** [comment]
@rtm Again, I think you were testing with browser and accountchooser is enabled. In this case, cancel button is hidden. If you disable accountchooser, you will see the cancel button.

**Comment by nicolasgarnier** [comment]
@rtm you can customize the look and feel of the widget using CSS, not sure if this will fix all your issues but at least you can get rid of the white square background.

For instance in my app I've been using this to make the widget transparent:

```css
#firebaseui-auth-container {
  min-width: 251px;
}
.firebaseui-container {
  background: rgba(0,0,0,0.05);
  margin-bottom: 15px;
  padding-top: 10px;
  border-radius: 20px;
  box-shadow: none;
}
.firebaseui-container.firebaseui-page-provider-sign-in {
  background: transparent;
  box-shadow: none;
  min-height: 0;
  margin-bottom: 0;
  padding-top: 0;
}
.firebaseui-container.firebaseui-id-page-callback {
  background: transparent;
  box-shadow: none;
  margin-top: 40px;
  height: 84px;
  min-height: 0;
  margin-bottom: 0;
  padding-top: 0;
}
.firebaseui-card-header {
  display: none;
}
.firebaseui-subtitle, .firebaseui-text {
  color: rgba(255,255,255,0.87);
}
.firebaseui-form-actions .mdl-button--raised.mdl-button--colored.firebaseui-button {
  background: rgba(0,0,0,0.1);
}
.firebaseui-id-dismiss-info-bar {
  display: block;
}
.firebaseui-info-bar {
  border: 0;
  border-radius: 10px;
  left: 5%;
  right: 5%;
  top: 10%;
  bottom: 10%;
}
```

Similarly, using CSS you can hide the loading animation or add some text before it (using the `::before` selector and the `content` attribute).

Also, are you using the redirect flow? If you can use the popup flow I've found it to be faster and it won't reload your app. Maybe you could try that.
